### ISSUE TITLE
osmosis 0.46 crashes with latest mapsforge-map-writer 0.8.0 running on FreeBSD

### ISSUE THREAD

**Issue by DeyanVasilev** [mapsforge/mapsforge#1007]
Freebsd 10.3 R, OpenJDK Runtime Environment (build 1.8.0_144-b01) with osmosis 0.46 and mapsforge-map-writer-0.8.0-jar-with-dependencies.jar that I got from maven.org.

command line:
osmosis --rb file=bgm_planet-2017-10-16T18:09:15Z.pbf --mapfile-writer file=bgm8.map bbox=42.05875,22.62349,43.31964,27.85863

Error that I got is (partial, beginning omitted):

Oct 17, 2017 2:13:38 AM org.mapsforge.map.writer.MapFileWriter writeSubfile
INFO: written 50% of sub file for zoom interval 3 (14,12,21)
Oct 17, 2017 2:13:47 AM org.mapsforge.map.writer.MapFileWriter writeSubfile
INFO: written 60% of sub file for zoom interval 3 (14,12,21)
Oct 17, 2017 2:13:54 AM org.mapsforge.map.writer.MapFileWriter writeSubfile
INFO: written 70% of sub file for zoom interval 3 (14,12,21)
Oct 17, 2017 2:13:59 AM org.mapsforge.map.writer.MapFileWriter writeSubfile
INFO: written 80% of sub file for zoom interval 3 (14,12,21)
Oct 17, 2017 2:14:06 AM org.mapsforge.map.writer.MapFileWriter writeSubfile
INFO: written 90% of sub file for zoom interval 3 (14,12,21)
Oct 17, 2017 2:14:13 AM org.mapsforge.map.writer.MapFileWriter writeFile
INFO: JTS Geometry cache hit rate: 1.0
Oct 17, 2017 2:14:13 AM org.mapsforge.map.writer.MapFileWriter writeFile
INFO: JTS Geometry total load time: 0
Oct 17, 2017 2:14:13 AM org.mapsforge.map.writer.MapFileWriter writeFile
INFO: Finished writing file.
Oct 17, 2017 2:14:13 AM org.mapsforge.map.writer.osmosis.MapFileWriterTask complete
INFO: finished...
Oct 17, 2017 2:14:13 AM org.mapsforge.map.writer.osmosis.MapFileWriterTask complete
INFO: estimated memory consumption: 2,098.78MB
Oct 17, 2017 2:14:13 AM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 1-rb failed
java.lang.AbstractMethodError: org.mapsforge.map.writer.osmosis.MapFileWriterTask.close()V
        at crosby.binary.osmosis.OsmosisReader.run(OsmosisReader.java:50)
        at java.lang.Thread.run(Thread.java:748)

Oct 17, 2017 2:14:14 AM org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.
org.openstreetmap.osmosis.core.OsmosisRuntimeException: One or more tasks failed.
        at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.waitForCompletion(Pipeline.java:146)
        at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:92)
        at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:47)

File bgm8.map is being created, probably a partial one. When uploaded to Oruxmaps, hangs app abilities to read online maps.

Can you please share what can be the reason for the osmosis crash above?

**Comment by devemux86** [comment]
As seen in main [Changelog](https://github.com/mapsforge/mapsforge/blob/master/docs/Changelog.md) or in map-writer [Changelog](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Map-Writer.md#changelog), Osmosis 0.46 is compatible with map-writer versions > 0.8.0, due to API changes introduced in latest Osmosis.

So you can use either Osmosis 0.45 with map-writer 0.8.0 or Osmosis 0.46 with map-writer[ snapshot version](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Map-Writer.md#plugin-installation).
