### ISSUE TITLE
java.lang.AbstractMethodError: org.mapsforge.map.writer.osmosis.MapFileWriterTask.close()V

### ISSUE THREAD

**Issue by Lacredin** [mapsforge/mapsforge#1008]
Good day!
I'm trying to convert osm files into map files (mapsforge).
I work from under Windows, osmosis version - 0.46, version of the plugin mapsforge 0.8. All the latest.
Rendering include this command:
C: \ Osmosis \ bin> osmosis --rx file = "C: \ Osmosis \ map \ RU-BEL.osm" --mapfile-writer file = "C: \ Osmosis \ map \ test.map"
But after several minutes of work produces an error, here is the log of work:

C:\Osmosis\bin>osmosis --rx file="C:\Osmosis\map\RU-BEL.osm" --mapfile-writer file="C:\Osmosis\map\test.map"
юъЄ 24, 2017 11:20:07 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Osmosis Version 0.46
юъЄ 24, 2017 11:20:07 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Preparing pipeline.
юъЄ 24, 2017 11:20:07 PM org.mapsforge.map.writer.osmosis.MapFileWriterTask <init>
INFO: mapfile-writer version: mapsforge-map-writer-0.8.0
юъЄ 24, 2017 11:20:07 PM org.mapsforge.map.writer.osmosis.MapFileWriterTask <init>
INFO: mapfile format specification version: 3
юъЄ 24, 2017 11:20:07 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Launching pipeline execution.
юъЄ 24, 2017 11:20:07 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Pipeline executing, waiting for completion.
юъЄ 24, 2017 11:20:07 PM org.mapsforge.map.writer.osmosis.MapFileWriterTask process
INFO: start reading data...
юъЄ 24, 2017 11:22:58 PM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 1-rx failed
java.lang.AbstractMethodError: org.mapsforge.map.writer.osmosis.MapFileWriterTask.close()V
        at org.openstreetmap.osmosis.xml.v0_6.XmlReader.run(XmlReader.java:107)
        at java.lang.Thread.run(Unknown Source)

юъЄ 24, 2017 11:22:59 PM org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.
org.openstreetmap.osmosis.core.OsmosisRuntimeException: One or more tasks failed.
        at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.waitForCompletion(Pipeline.java:146)
        at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:92)
        at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:47)

If you use a small size osm, then a map file is created, but the error appears in any case.

**Comment by devemux86** [comment]
Please see my answer here https://github.com/mapsforge/mapsforge/issues/1007#issuecomment-337125222.
