### ISSUE TITLE
Error using mapsforge-map-writer-0.9.0-jar-with-dependencies

### ISSUE THREAD

**Issue by txtdis** [mapsforge/mapsforge#1022]
After updating to mapsforge-map-writer-0.9.0-jar-with-dependencies from 0.8.0, when running:
	osmosis.bat --rb file=area.pbf --mapfile-writer file=area.map polygon-clipping=false way-clipping=false 
I now get the following error, which I did not with the previous:

Dec 21, 2017 7:56:12 AM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 1-rb failed
java.lang.AbstractMethodError: org.mapsforge.map.writer.osmosis.MapFileWriterTask.release()V
    at crosby.binary.osmosis.OsmosisReader.run(OsmosisReader.java:50)
	at java.lang.Thread.run(Unknown Source)

Dec 21, 2017 7:56:12 AM org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.                                                                                              org.openstreetmap.osmosis.core.OsmosisRuntimeException: One or more tasks failed.
    at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.waitForCompletion(Pipeline.java:146)
	at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:92)
	at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)

**Comment by devemux86** [comment]
Map writer 0.9.0 works with the latest [Osmosis 0.46](http://wiki.openstreetmap.org/wiki/Osmosis) release.
(can be seen in Mapsforge changelog [here](https://github.com/mapsforge/mapsforge/blob/master/docs/Changelog.md) or [here](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Map-Writer.md#changelog))
