### ISSUE TITLE
exception on layer clear: java.lang.IllegalStateException: layer is not assigned

### ISSUE THREAD

**Issue by drakkan** [mapsforge/mapsforge#1053]
I sometime get this exception after doing mMapView.getLayerManager().getLayers().clear();

here is the stack trace:

```
java.lang.IllegalStateException: layer is not assigned
at org.mapsforge.map.layer.Layer.unassign(SourceFile:166)
at org.mapsforge.map.layer.Layers.clear(SourceFile:210)
at org.mapsforge.map.layer.Layers.clear(SourceFile:199)
....
....
at org.mapsforge.map.model.common.Observable.notifyObservers(SourceFile:46)
at org.mapsforge.map.model.MapViewPosition.moveCenterAndZoom(SourceFile:319)
at org.mapsforge.map.model.MapViewPosition.moveCenterAndZoom(SourceFile:293)
at org.mapsforge.map.android.input.TouchGestureHandler.onScaleEnd(SourceFile:209)
at android.view.ScaleGestureDetector.onTouchEvent(ScaleGestureDetector.java:407)
at org.mapsforge.map.android.view.MapView.onTouchEvent(SourceFile:423)
at android.view.View.dispatchTouchEvent(View.java:8476)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2092)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
```

based on zoom level I clear the layers and add different markers

**Comment by devemux86** [comment]
Don't know your implementation, but if want to remove a layer, should not clear the whole list and expect to keep using the map without content.
Can check [LongPressAction](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/LongPressAction.java) where is demonstrated the add / remove of overlays.

For questions and discussion please use the [forum](https://groups.google.com/group/mapsforge-dev) first. If an actual problem arises, then can create issues for improve or fix.
