### ISSUE TITLE
Error E/idPoiPersistenceManager:

### ISSUE THREAD

**Issue by 35776558** [mapsforge/mapsforge#1075]
```java
E/idPoiPersistenceManager: unknown error in open
                           jsqlite.Exception: unknown error in open
                               at jsqlite.Database._open4(Native Method)
                               at jsqlite.Database.open(Database.java:37)
                               at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManager.createOrOpenDBFile(AndroidPoiPersistenceManager.java:198)
                               at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManager.<init>(AndroidPoiPersistenceManager.java:73)
                               at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManagerFactory.getPoiPersistenceManager(AndroidPoiPersistenceManagerFactory.java:42)
                               at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManagerFactory.getPoiPersistenceManager(AndroidPoiPersistenceManagerFactory.java:32)
                               at org.mapsforge.samples.android.PoiSearchViewer.onCreate(PoiSearchViewer.java:80)
                               at android.app.Activity.performCreate(Activity.java:6672)
                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
                               at android.app.ActivityThread.-wrap12(ActivityThread.java)
                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
                               at android.os.Handler.dispatchMessage(Handler.java:102)
                               at android.os.Looper.loop(Looper.java:154)
                               at android.app.ActivityThread.main(ActivityThread.java:6123)
                               at java.lang.reflect.Method.invoke(Native Method)
                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
E/idPoiPersistenceManager: database already closed
                           jsqlite.Exception: database already closed
                               at jsqlite.Database.stmt_prepare(Native Method)
                               at jsqlite.Database.prepare(Database.java:718)
                               at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManager.readPoiFileInfo(AndroidPoiPersistenceManager.java:507)
                               at org.mapsforge.poi.storage.AbstractPoiPersistenceManager.getPoiFileInfo(AbstractPoiPersistenceManager.java:84)
                               at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManager.isValidDataBase(AndroidPoiPersistenceManager.java:469)
                               at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManager.createOrOpenDBFile(AndroidPoiPersistenceManager.java:205)
                               at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManager.<init>(AndroidPoiPersistenceManager.java:73)
                               at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManagerFactory.getPoiPersistenceManager(AndroidPoiPersistenceManagerFactory.java:42)
                               at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManagerFactory.getPoiPersistenceManager(AndroidPoiPersistenceManagerFactory.java:32)
                               at org.mapsforge.samples.android.PoiSearchViewer.onCreate(PoiSearchViewer.java:80)
                               at android.app.Activity.performCreate(Activity.java:6672)
                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
                               at android.app.ActivityThread.-wrap12(ActivityThread.java)
                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
                               at android.os.Handler.dispatchMessage(Handler.java:102)
                               at android.os.Looper.loop(Looper.java:154)
                               at android.app.ActivityThread.main(ActivityThread.java:6123)
                               at java.lang.reflect.Method.invoke(Native Method)
                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
E/idPoiPersistenceManager: database already closed
                           jsqlite.Exception: database already closed
                               at jsqlite.Database.stmt_prepare(Native Method)
                               at jsqlite.Database.prepare(Database.java:718)
                               at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManager.isValidDataBase(AndroidPoiPersistenceManager.java:472)
                               at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManager.createOrOpenDBFile(AndroidPoiPersistenceManager.java:205)
                               at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManager.<init>(AndroidPoiPersistenceManager.java:73)
                               at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManagerFactory.getPoiPersistenceManager(AndroidPoiPersistenceManagerFactory.java:42)
                               at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManagerFactory.getPoiPersistenceManager(AndroidPoiPersistenceManagerFactory.java:32)
                               at org.mapsforge.samples.android.PoiSearchViewer.onCreate(PoiSearchViewer.java:80)
                               at android.app.Activity.performCreate(Activity.java:6672)
                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
                               at android.app.ActivityThread.-wrap12(ActivityThread.java)
                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
                               at android.os.Handler.dispatchMessage(Handler.java:102)
                               at android.os.Looper.loop(Looper.java:154)
                               at android.app.ActivityThread.main(ActivityThread.java:6123)
                               at java.lang.reflect.Method.invoke(Native Method)
                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
E/idPoiPersistenceManager: Attempt to invoke virtual method 'boolean jsqlite.Stmt.step()' on a null object reference
                           java.lang.NullPointerException: Attempt to invoke virtual method 'boolean jsqlite.Stmt.step()' on a null object reference
                               at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManager.isValidDataBase(AndroidPoiPersistenceManager.java:484)
                               at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManager.createOrOpenDBFile(AndroidPoiPersistenceManager.java:205)
                               at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManager.<init>(AndroidPoiPersistenceManager.java:73)
                               at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManagerFactory.getPoiPersistenceManager(AndroidPoiPersistenceManagerFactory.java:42)
                               at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManagerFactory.getPoiPersistenceManager(AndroidPoiPersistenceManagerFactory.java:32)
                               at org.mapsforge.samples.android.PoiSearchViewer.onCreate(PoiSearchViewer.java:80)
                               at android.app.Activity.performCreate(Activity.java:6672)
                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
                               at android.app.ActivityThread.-wrap12(ActivityThread.java)
                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
                               at android.os.Handler.dispatchMessage(Handler.java:102)
                               at android.os.Looper.loop(Looper.java:154)
                               at android.app.ActivityThread.main(ActivityThread.java:6123)
                               at java.lang.reflect.Method.invoke(Native Method)
                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
E/droidPoiCategoryManager: database already closed
                           jsqlite.Exception: database already closed
                               at jsqlite.Database.stmt_prepare(Native Method)
                               at jsqlite.Database.prepare(Database.java:718)
                               at org.mapsforge.poi.android.storage.AndroidPoiCategoryManager.loadCategories(AndroidPoiCategoryManager.java:68)
                               at org.mapsforge.poi.android.storage.AndroidPoiCategoryManager.<init>(AndroidPoiCategoryManager.java:49)
                               at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManager.<init>(AndroidPoiPersistenceManager.java:76)
                               at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManagerFactory.getPoiPersistenceManager(AndroidPoiPersistenceManagerFactory.java:42)
                               at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManagerFactory.getPoiPersistenceManager(AndroidPoiPersistenceManagerFactory.java:32)
                               at org.mapsforge.samples.android.PoiSearchViewer.onCreate(PoiSearchViewer.java:80)
                               at android.app.Activity.performCreate(Activity.java:6672)
                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
                               at android.app.ActivityThread.-wrap12(ActivityThread.java)
                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
                               at android.os.Handler.dispatchMessage(Handler.java:102)
                               at android.os.Looper.loop(Looper.java:154)
                               at android.app.ActivityThread.main(ActivityThread.java:6123)
                               at java.lang.reflect.Method.invoke(Native Method)
                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
E/droidPoiCategoryManager: null
                           org.mapsforge.poi.storage.UnknownPoiCategoryException
                               at org.mapsforge.poi.storage.AbstractPoiCategoryManager.getPoiCategoryByID(AbstractPoiCategoryManager.java:43)
                               at org.mapsforge.poi.android.storage.AndroidPoiCategoryManager.loadCategories(AndroidPoiCategoryManager.java:93)
                               at org.mapsforge.poi.android.storage.AndroidPoiCategoryManager.<init>(AndroidPoiCategoryManager.java:49)
                               at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManager.<init>(AndroidPoiPersistenceManager.java:76)
                               at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManagerFactory.getPoiPersistenceManager(AndroidPoiPersistenceManagerFactory.java:42)
                               at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManagerFactory.getPoiPersistenceManager(AndroidPoiPersistenceManagerFactory.java:32)
                               at org.mapsforge.samples.android.PoiSearchViewer.onCreate(PoiSearchViewer.java:80)
                               at android.app.Activity.performCreate(Activity.java:6672)
                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
                               at android.app.ActivityThread.-wrap12(ActivityThread.java)
                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
                               at android.os.Handler.dispatchMessage(Handler.java:102)
                               at android.os.Looper.loop(Looper.java:154)
                               at android.app.ActivityThread.main(ActivityThread.java:6123)
                               at java.lang.reflect.Method.invoke(Native Method)
                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```
Me sale este error cuando quiero encontrar los puntos de interes en un mapa de argentina.

**Comment by devemux86** [comment]
There is [PoiSearchViewer](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/PoiSearchViewer.java) example in samples which works and demonstrates the POI search usage.

Need to follow its implementation for open properly a .poi file and search for a category that exists in it.

**Comment by 35776558** [comment]
descargue el ejemplo y descargue los mapas argentina.poi y argentina.map y los puse en la memoria extrerna.. al debug la app me encuentro con ese error..

**Comment by devemux86** [comment]
Like mentioned above and also in instructions dialog when the sample starts, need to have the .poi file renamed to germany.poi in storage or change in code the loaded .poi file to your filename.
