### ISSUE TITLE
Problems when using Poi

### ISSUE THREAD

**Issue by peisong0109** [mapsforge/mapsforge#1077]
How can I search for a place in the map?
I hope I can get your help, thank you very much.

`08-12 18:58:38.719 28957-28957/? E/Zygote: isWhitelistProcess - Process is Whitelisted
08-12 18:58:38.720 28957-28957/? E/libpersona: scanKnoxPersonas
    Couldn't open the File - /data/system/users/0/personalist.xml - No such file or directory
08-12 18:58:38.861 28957-28965/? E/zygote: Failed writing handshake bytes (-1 of 14): Broken pipe
08-12 18:58:40.991 28957-28957/com.example.administrator.poi_test E/idPoiPersistenceManager: no such column: poi_data.category
    jsqlite.Exception: no such column: poi_data.category
        at jsqlite.Database.stmt_prepare(Native Method)
        at jsqlite.Database.prepare(Database.java:718)
        at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManager.<init>(AndroidPoiPersistenceManager.java:71)
        at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManagerFactory.getPoiPersistenceManager(AndroidPoiPersistenceManagerFactory.java:42)
        at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManagerFactory.getPoiPersistenceManager(AndroidPoiPersistenceManagerFactory.java:32)
        at com.example.administrator.poi_test.PoiSearchViewer.onCreate(PoiSearchViewer.java:89)
        at android.app.Activity.performCreate(Activity.java:7174)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

**Comment by devemux86** [comment]
For questions please use the [forum](https://groups.google.com/forum/#!forum/mapsforge-dev).

Can check [PoiSearchViewer](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/PoiSearchViewer.java) example in samples which demonstrates the POI search.
