### ISSUE TITLE
mapsforge-poi-writer - Runtime error on OpenJDK 10

### ISSUE THREAD

**Issue by mstaniszczak** [mapsforge/mapsforge#1083]
Hi, running the latest available JAR file (snapshot from 20180824) I get a runtime error:

```
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.mapsforge.poi.writer.PoiWriter.<init>(PoiWriter.java:133)
	at org.mapsforge.poi.writer.PoiWriter.newInstance(PoiWriter.java:76)
	at org.mapsforge.poi.writer.osmosis.PoiWriterTask.<init>(PoiWriterTask.java:66)
	at org.mapsforge.poi.writer.osmosis.PoiWriterFactory.createTaskManagerImpl(PoiWriterFactory.java:84)
	at org.openstreetmap.osmosis.core.pipeline.common.TaskManagerFactory.createTaskManager(TaskManagerFactory.java:60)
	at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.buildTasks(Pipeline.java:51)
	at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.prepare(Pipeline.java:112)
	at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:86)
	at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at org.java.plugin.standard.StandardPluginClassLoader.loadClass(StandardPluginClassLoader.java:330)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 18 more
```
Java version:

```
$ java --version
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.1)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.1, mixed mode)
```

**Comment by devemux86** [comment]
https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

**Comment by mstaniszczak** [comment]
Any reason to just not add:

```
implementation 'javax.xml.bind:jaxb-api:2.3.0'
```
to gradle? I'll test it in a while.

**Comment by devemux86** [comment]
Just mentioned a search result with the reasons, as have not seen the issue so far. :slightly_smiling_face: 

If doesn't break experience in previous Java for users, we can add the dependency.

Does the map-writer shows similar behaviour?

**Comment by mstaniszczak** [comment]
Nop, but like I see map-writer not use javax.xml.bind.

**Comment by mstaniszczak** [comment]
Yes. I using it with https://github.com/mapsforge/mapsforge-creator, which use both, map-writer and poi-writer. map-writer woks fine without changes.

**Comment by devemux86** [comment]
I tested the dependency in older Java and not seen any issues.
If you can test it also in your environment and works, then can add it.

**Comment by devemux86** [comment]
Actually need to change the `ClassLoader` in `JAXBContext` to make it work.

**Comment by devemux86** [comment]
Actually need some different dependencies and change the `ClassLoader` in `JAXBContext` to make it work.

**Comment by mstaniszczak** [comment]
I went to the BBQ last night. I wanted to check it today once again + send a PR. But I see that you already made fix for it. Thanks!
