### ISSUE TITLE
Android: Corrupted tiles with TileDownloadLayer

### ISSUE THREAD

**Issue by mopfattn** [mapsforge/mapsforge#1096]
I'm using the TileDownloadLayer with different map styles (OpenStreetMap, OpenCycleMap) on Android, MapsForge 0.10.0.

Every time I change the map style I remove and destroy the old layer to make sure the download threads are stopped. When a download is still in progress, I end up with an exception and sometimes a corrupted tile is saved to the cache.

```
2019-01-01 11:59:13.870 30662-30998/*** W/System.err: java.io.InterruptedIOException: thread interrupted
2019-01-01 11:59:13.870 30662-30998/*** W/System.err:     at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:145)
2019-01-01 11:59:13.870 30662-30998/*** W/System.err:     at com.android.okhttp.okio.Okio$2.read(Okio.java:133)
2019-01-01 11:59:13.870 30662-30998/*** W/System.err:     at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
2019-01-01 11:59:13.870 30662-30998/*** W/System.err:     at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)
2019-01-01 11:59:13.870 30662-30998/*** W/System.err:     at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:393)
2019-01-01 11:59:13.870 30662-30998/*** W/System.err:     at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
2019-01-01 11:59:13.870 30662-30998/*** W/System.err:     at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
2019-01-01 11:59:13.870 30662-30998/*** W/System.err:     at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:756)
2019-01-01 11:59:13.870 30662-30998/*** W/System.err:     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:731)
2019-01-01 11:59:13.870 30662-30998/*** W/System.err:     at org.mapsforge.map.android.graphics.AndroidTileBitmap.<init>(AndroidTileBitmap.java:114)
2019-01-01 11:59:13.870 30662-30998/*** W/System.err:     at org.mapsforge.map.android.graphics.AndroidGraphicFactory.createTileBitmap(AndroidGraphicFactory.java:267)
2019-01-01 11:59:13.870 30662-30998/*** W/System.err:     at org.mapsforge.map.layer.download.TileDownloader.downloadImage(TileDownloader.java:74)
2019-01-01 11:59:13.870 30662-30998/*** W/System.err:     at org.mapsforge.map.layer.download.TileDownloadThread.downloadTile(TileDownloadThread.java:81)
2019-01-01 11:59:13.870 30662-30998/*** W/System.err:     at org.mapsforge.map.layer.download.TileDownloadThread.doWork(TileDownloadThread.java:60)
2019-01-01 11:59:13.870 30662-30998/*** W/System.err:     at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)
```

On the next start I get one of these corrupted tiles from the cache, which then looks like this:

![device-2019-01-01-121057](https://user-images.githubusercontent.com/3525038/50572346-ecd77000-0dbe-11e9-88fc-a26a7a2233b9.png)

**Comment by devemux86** [comment]
Could depends on implementation, since have not seen any problem when change map sources.

As seen in [DownloadLayerViewer](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/DownloadLayerViewer.java) or [RenderThemeChanger](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/RenderThemeChanger.java) or [TileSizeChanger](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/TileSizeChanger.java) and other samples, old map needs first to be stopped, old cache can be deleted and then create new map with new cache folder or use old *empty* one.
