### ISSUE TITLE
ArrayIndexOutOfBoundsException in TouchGestureHandler

### ISSUE THREAD

**Issue by cl90** [mapsforge/mapsforge#1114]
I got the following exception using mapsforge in an Android App on device running Android Pie:

```
    java.lang.ArrayIndexOutOfBoundsException: length=4; index=4
        at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:385)
        at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:398)
        at org.mapsforge.map.layer.Layers.get(Layers.java:230)
        at org.mapsforge.map.android.input.TouchGestureHandler.onSingleTapConfirmed(TouchGestureHandler.java:253)
        at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
There seems to be a related issue in cgeo: https://github.com/cgeo/cgeo/issues/7034

In fact my application adds and removes layers on a background thread. Please let me know if this is considered to be bad practise.

**Comment by devemux86** [comment]
Can follow the advice in the mentioned issue and handle the layers in UI thread?

**Comment by cl90** [comment]
Basically I can, but this may result in blocking the UI thread for up to a few seconds when adding/removing layers, because LayerManager holds a lock:

```
"LayerManager@16443" prio=5 tid=0x6df nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	 blocks main@10640
	  at android.graphics.BaseCanvas.nDrawBitmapMatrix(BaseCanvas.java:-1)
	  at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:118)
	  at android.graphics.Canvas.drawBitmap(Canvas.java:1556)
	  at org.mapsforge.map.android.graphics.AndroidCanvas.drawBitmap(AndroidCanvas.java:133)
	  at org.mapsforge.map.layer.TileLayer.drawParentTileBitmap(TileLayer.java:189)
	  at org.mapsforge.map.layer.TileLayer.draw(TileLayer.java:104)
	  at org.mapsforge.map.layer.download.TileDownloadLayer.draw(TileDownloadLayer.java:57)
	  at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:95)
	  - locked <0x4344> (a org.mapsforge.map.layer.Layers)
	  at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)
```

BTW: I used to handle layers on the main thread in an earlier version, but UI lags seem to have increased as of mpasforge version 0.10.0 (and are still present in version 0.11.0), so I'm trying to move it to a background thread.

**Comment by devemux86** [comment]
For questions and discussion please use the [forum](https://groups.google.com/group/mapsforge-dev).

**Comment by eddiemuc** [comment]
PR https://github.com/mapsforge/mapsforge/pull/1256 would fix this too
