### ISSUE TITLE
deadlock on mapView destroyAll #1058 still occuring

### ISSUE THREAD

**Issue by cl90** [mapsforge/mapsforge#1126]
See discussion in #1058 

I still get the same problem with mapsforge 0.11.0 when quickly initializing/destroying a map view.

```
"main@10640" prio=5 tid=0x2 nid=NA waiting
  java.lang.Thread.State: WAITING
	 blocks main@10640
	  at java.lang.Object.wait(Object.java:-1)
	  at org.mapsforge.map.view.FrameBufferBitmap$Lock.waitDisabled(FrameBufferBitmap.java:67)
	  - locked <0x3e81> (a org.mapsforge.map.view.FrameBufferBitmap$Lock)
	  at org.mapsforge.map.view.FrameBufferBitmap.destroy(FrameBufferBitmap.java:101)
	  at org.mapsforge.map.view.FrameBufferHA2.destroy(FrameBufferHA2.java:70)
	  - locked <0x3e82> (a org.mapsforge.map.view.FrameBufferHA2)
	  at org.mapsforge.map.android.view.MapView.destroy(MapView.java:191)
	  at org.mapsforge.map.android.view.MapView.destroyAll(MapView.java:218)
```

**Comment by devemux86** [comment]
Let's not have multiple similar issues (I reopened #1058).

**Comment by cl90** [comment]
Agreed. Thanks.
