### ISSUE TITLE
Cannot invoke "org.oscim.backend.CanvasAdapter.newCanvasImpl()" because "org.oscim.backend.CanvasAdapter.g" is null

### ISSUE THREAD

**Issue by amicharski** [mapsforge/mapsforge#1235]
I'm getting this error when debugging:
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.oscim.backend.CanvasAdapter.newCanvasImpl()" because "org.oscim.backend.CanvasAdapter.g" is null
	at org.oscim.backend.CanvasAdapter.newCanvas(CanvasAdapter.java:87)
	at UserInterface.showUI(UserInterface.java:17)
	at UserInterface.<init>(UserInterface.java:11)
	at UserInterface.main(UserInterface.java:25)
```
Here is my maven:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>Magellan</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>15</maven.compiler.source>
        <maven.compiler.target>15</maven.compiler.target>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.mapsforge</groupId>
            <artifactId>vtm-desktop</artifactId>
            <version>0.16.0</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.5</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>1.7.5</version>
        </dependency>
    </dependencies>

</project>
```

And this is my code:
```java
import org.oscim.awt.AwtGraphics;
import org.oscim.backend.canvas.Canvas;

import javax.swing.*;
import java.awt.*;


public class UserInterface {


    public UserInterface(){ showUI(); }

    private void showUI(){
        JFrame jFrame = new JFrame();
        jFrame.setSize(500, 500);

        Canvas canvas = AwtGraphics.newCanvas();
        Container container = jFrame.getContentPane();
        container.setLayout(new BorderLayout());
        container.add((Component) canvas);
        jFrame.setVisible(true);
        jFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public static void main(String[] args){ new UserInterface(); }
}
```

**Comment by devemux86** [comment]
You probably mean [VTM](https://github.com/mapsforge/vtm) library. This is Mapsforge repository.

---

_For questions, reports and feature requests please use the Discussions._
