### ISSUE TITLE
SQLite Error when adding or removing POI's using the AwtPoiPersistanceManager

### ISSUE THREAD

**Issue by fltodd** [mapsforge/mapsforge#1375]
Any time I try to add or remove a POI from a .poi file (specifically england.poi from https://download.mapsforge.org/pois/europe/great-britain/) sever SQL Errors are thrown.

Code Used:
```java
public static void main(String args[]) {
	PoiPersistenceManager persistenceManager = AwtPoiPersistenceManagerFactory.getPoiPersistenceManager("england.poi");
	PoiCategory category;
	try {
		category = persistenceManager.getCategoryManager().getRootCategory();
		PointOfInterest poi = new PointOfInterest(0, 55, -1, "Test Poi", category);
		persistenceManager.insertPointOfInterest(poi);
		System.out.println("Inserted POI");
		persistenceManager.removePointOfInterest(poi);
		System.out.println("Removed POI");
	} catch (UnknownPoiCategoryException e) {
		e.printStackTrace();
	}
}
```
Console Output:
```java
Dec 15, 2022 6:32:56 PM org.mapsforge.poi.awt.storage.AwtPoiPersistenceManager insertPointsOfInterest
SEVERE: [SQLITE_ERROR] SQL error or missing database (cannot start a transaction within a transaction)
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (cannot start a transaction within a transaction)
	at org.sqlite.core.DB.newSQLException(DB.java:941)
	at org.sqlite.core.DB.newSQLException(DB.java:953)
	at org.sqlite.core.DB.execute(DB.java:857)
	at org.sqlite.core.CoreStatement.exec(CoreStatement.java:80)
	at org.sqlite.jdbc3.JDBC3Statement.execute(JDBC3Statement.java:53)
	at org.mapsforge.poi.awt.storage.AwtPoiPersistenceManager.insertPointsOfInterest(AwtPoiPersistenceManager.java:465)
	at org.mapsforge.poi.awt.storage.AwtPoiPersistenceManager.insertPointOfInterest(AwtPoiPersistenceManager.java:441)
	at MapDemo.WindowedMap.main(WindowedMap.java:76)
Inserted POI
Dec 15, 2022 6:32:56 PM org.mapsforge.poi.awt.storage.AwtPoiPersistenceManager removePointOfInterest
SEVERE: [SQLITE_ERROR] SQL error or missing database (cannot start a transaction within a transaction)
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (cannot start a transaction within a transaction)
	at org.sqlite.core.DB.newSQLException(DB.java:941)
	at org.sqlite.core.DB.newSQLException(DB.java:953)
	at org.sqlite.core.DB.execute(DB.java:857)
	at org.sqlite.core.CoreStatement.exec(CoreStatement.java:80)
	at org.sqlite.jdbc3.JDBC3Statement.execute(JDBC3Statement.java:53)
	at org.mapsforge.poi.awt.storage.AwtPoiPersistenceManager.removePointOfInterest(AwtPoiPersistenceManager.java:628)
	at MapDemo.WindowedMap.main(WindowedMap.java:78)
Removed POI
```

**Comment by devemux86** [comment]
Thanks for the report.

This was working, at least when implemented.
Has something changed in the JDBC driver?

Can you check the merged change and see if it works properly?
