### ISSUE TITLE
TileDownloader fails in Android Studio

### ISSUE THREAD

**Issue by yschimke** [mapsforge/mapsforge#1419]
See https://buganizer.corp.google.com/issues/289769163

Simple workaround is probably pulling up the getInputStream call.

```
class TileDownloader {
    private static InputStream getInputStream(URLConnection urlConnection) throws IOException {
        InputStream is = urlConnection.getInputStream();
        if ("gzip".equals(urlConnection.getContentEncoding())) {
            return new GZIPInputStream(is);
        }
        return is;
    }
```

**Comment by devemux86** [comment]
What do you mean?

[DownloadLayerViewer](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/DownloadLayerViewer.java) seems to work properly on latest Android.

**Comment by yschimke** [comment]
Getting this exception running on emulator in Android Studio

```
                 Process: de.tadris.fitness.debug, PID: 3121
                 java.lang.IllegalStateException: Cannot access request header fields after connection is set
                 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getRequestProperties(HttpURLConnectionImpl.java:236)
                 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getRequestProperties(DelegatingHttpsURLConnection.java:183)
                 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getRequestProperties(HttpsURLConnectionImpl.java:30)
                 	at com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.getRequestProperties(TrackedHttpURLConnection.java:230)
                 	at com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.trackPreConnect(TrackedHttpURLConnection.java:63)
                 	at com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.getInputStream(TrackedHttpURLConnection.java:372)
                 	at com.android.tools.profiler.support.network.httpurl.HttpsURLConnection$.getInputStream(HttpsURLConnection$.java:261)
                 	at org.mapsforge.map.layer.download.TileDownloader.getInputStream(TileDownloader.java:37)
                 	at org.mapsforge.map.layer.download.TileDownloader.downloadImage(TileDownloader.java:71)
                 	at org.mapsforge.map.layer.download.TileDownloadThread.downloadTile(TileDownloadThread.java:81)
                 	at org.mapsforge.map.layer.download.TileDownloadThread.doWork(TileDownloadThread.java:60)
                 	at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)
```

**Comment by devemux86** [comment]
I cannot reproduce it or have seen such exception while using Mapsforge.

But we could make the change you suggest.
Do you want to send a pull request?

**Comment by red0bear** [comment]
@devemux86 , may be he is set wrong the packages and forget some permissions and something missing.

**Comment by yschimke** [comment]
It's an Android Studio inspector bug. Consider this a heads up in case you see it. Since the workaround looks simple, I thought worth mentioning.

Feel free to close.
