### ISSUE TITLE
mapsforge-poi-writer 0.20.0 reported an exception: [SQLITE_ERROR] SQL error or missing database (no such column: poi_data.data)

### ISSUE THREAD

**Issue by alpha-rudy** [mapsforge/mapsforge#1440]
Hi, 

I changed from v2 POI (poi-writer 0.18.0) to v3 POI (poi-writer 0.20.0), and met an error. 

The options I used for poi-writer:
```
--poi-writer \
  all-tags=true \
  geo-tags=true \
  names=false \
  bbox=23.226,120.822,23.578,121.249 \
  ways=true \
  tag-conf-file="poi-mapping-3.xml" \
  comment="2023.09.04 / (c) Map data: OSM contributors" \
  file="generated.poi"
```

The exception I got:
```
INFO: Creating POI database...
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such column: poi_data.data)
	at org.sqlite.core.DB.newSQLException(DB.java:941)
	at org.sqlite.core.DB.newSQLException(DB.java:953)
	at org.sqlite.core.DB.throwex(DB.java:918)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
	at org.sqlite.core.DB.prepare(DB.java:257)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:47)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
	at org.mapsforge.poi.writer.GeoTagger.<init>(GeoTagger.java:64)
	at org.mapsforge.poi.writer.PoiWriter.<init>(PoiWriter.java:140)
	at org.mapsforge.poi.writer.PoiWriter.newInstance(PoiWriter.java:54)
	at org.mapsforge.poi.writer.osmosis.PoiWriterTask.<init>(PoiWriterTask.java:66)
	at org.mapsforge.poi.writer.osmosis.PoiWriterFactory.createTaskManagerImpl(PoiWriterFactory.java:87)
	at org.openstreetmap.osmosis.core.pipeline.common.TaskManagerFactory.createTaskManager(TaskManagerFactory.java:60)
	at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.buildTasks(Pipeline.java:51)
	at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.prepare(Pipeline.java:112)
	at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:86)
	at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
```

It seems SQL in maspforge-poi has a mistake.

Please help. Thank you!

Sincerely,
Rudy  9/4

**Comment by devemux86** [comment]
https://oss.sonatype.org/content/repositories/snapshots/org/mapsforge/mapsforge-poi-writer/master-SNAPSHOT/

**Comment by alpha-rudy** [comment]
Thank you very much, @devemux86 , it works.  :D

I would further test it with Cruiser.

One more question, what tags are generated with geo-tags?  XD

**Comment by alpha-rudy** [comment]
> Better check in the code, it was a community provided feature.
Got it, thank tou @devemux86.

Unfortuantely, I tested the generated POI with Cruiser 3.0.31. It said "Invalid POI". 

I check the metadata, it is indeed v3. Not sure why.
<img width="342" alt="Screenshot 2023-09-04 at 11 54 10 PM" src="https://github.com/mapsforge/mapsforge/assets/12744709/e40e9560-dda6-4c84-86f1-7ef33c167280">

Could you check?
https://www.dropbox.com/scl/fi/9lurq3gqffftgu9ctox0j/MOI_OSM_Taiwan_TOPO_Rudy-v3.poi.zip?rlkey=nuk2b428dgc44fivc4i92lhsc&dl=0

**Comment by alpha-rudy** [comment]
Yes, I did.  ^^

<img width="283" alt="Screenshot 2023-09-05 at 12 18 23 AM" src="https://github.com/mapsforge/mapsforge/assets/12744709/27efc22b-10b1-4464-905a-212e5e22ab71">

I "Search" > "Open POI", then "Search" > "Search", then I got an "Invalid poi" error.

**Comment by devemux86** [comment]
It works here (Linux) with your poi:

Also select some categories to avoid huge search results.

![Screenshot from 2023-09-04 19-22-49](https://github.com/mapsforge/mapsforge/assets/3484020/8cfbd18d-bcb0-4276-b218-cc666f22a2a9)

**Comment by devemux86** [comment]
@alpha-rudy 

Try with OpenJDK 17 (Temurin): https://adoptium.net

**Comment by alpha-rudy** [comment]
Hi, @devemux86 , I tried OpenJDK 17 and Oracle JDK 20, both have the same issue.

Do you know what should I install further?

`java.sql.SQLException: Error opening connection`

`Caused by: java.lang.Exception: No native library is found for os.name=Mac and os.arch=aarch64. path=/org/sqlite/native/Mac/aarch64`

```
rudyPro2:~ rudychung$ java --version
openjdk 17.0.8.1 2023-08-24
OpenJDK Runtime Environment Homebrew (build 17.0.8.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.8.1+0, mixed mode, sharing)

rudyPro2:cruiser rudychung$ bash ./cruiser.sh 
Sep 05, 2023 9:16:45 AM org.mapsforge.poi.awt.storage.AwtPoiPersistenceManager createOrOpenDBFile
SEVERE: Error opening connection
java.sql.SQLException: Error opening connection
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:239)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21)
	at org.sqlite.JDBC.createConnection(JDBC.java:115)
	at org.sqlite.JDBC.connect(JDBC.java:90)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)
	at org.mapsforge.poi.awt.storage.AwtPoiPersistenceManager.createOrOpenDBFile(AwtPoiPersistenceManager.java:186)
	at org.mapsforge.poi.awt.storage.AwtPoiPersistenceManager.<init>(AwtPoiPersistenceManager.java:59)
	at org.mapsforge.poi.awt.storage.AwtPoiPersistenceManagerFactory.getPoiPersistenceManager(AwtPoiPersistenceManagerFactory.java:39)
	at org.mapsforge.poi.awt.storage.AwtPoiPersistenceManagerFactory.getPoiPersistenceManager(AwtPoiPersistenceManagerFactory.java:29)
	at com.devemux86.poi.i.a(SourceFile:156)
	at com.devemux86.poi.i.c(SourceFile:168)
	at com.devemux86.poi.a.b(SourceFile:114)
	at com.devemux86.poi.i.f(SourceFile:233)
	at com.devemux86.poi.PoiLibrary.dialogSearch(SourceFile:116)
	at com.devemux86.cruiser.ck.actionPerformed(SourceFile:241)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028)
	at java.desktop/com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.Exception: No native library is found for os.name=Mac and os.arch=aarch64. path=/org/sqlite/native/Mac/aarch64
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:333)
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:64)
	at org.sqlite.core.NativeDB.load(NativeDB.java:63)
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:235)
	... 55 more
```

**Comment by alpha-rudy** [comment]
I tried OpenJDK 17 (Temurin), same result.  XD

```
rudyPro2:cruiser rudychung$ java --version
openjdk 17.0.8.1 2023-08-24
OpenJDK Runtime Environment Temurin-17.0.8.1+1 (build 17.0.8.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.8.1+1 (build 17.0.8.1+1, mixed mode)
rudyPro2:cruiser rudychung$ 
rudyPro2:cruiser rudychung$ java -Xmx1024M -jar cruiser.jar
Sep 05, 2023 9:49:42 AM org.mapsforge.poi.awt.storage.AwtPoiPersistenceManager createOrOpenDBFile
SEVERE: Error opening connection
java.sql.SQLException: Error opening connection
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:239)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21)
	at org.sqlite.JDBC.createConnection(JDBC.java:115)
	at org.sqlite.JDBC.connect(JDBC.java:90)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)
	at org.mapsforge.poi.awt.storage.AwtPoiPersistenceManager.createOrOpenDBFile(AwtPoiPersistenceManager.java:186)
	at org.mapsforge.poi.awt.storage.AwtPoiPersistenceManager.<init>(AwtPoiPersistenceManager.java:59)
	at org.mapsforge.poi.awt.storage.AwtPoiPersistenceManagerFactory.getPoiPersistenceManager(AwtPoiPersistenceManagerFactory.java:39)
	at org.mapsforge.poi.awt.storage.AwtPoiPersistenceManagerFactory.getPoiPersistenceManager(AwtPoiPersistenceManagerFactory.java:29)
	at com.devemux86.poi.i.a(SourceFile:156)
	at com.devemux86.poi.i.c(SourceFile:168)
	at com.devemux86.poi.a.b(SourceFile:114)
	at com.devemux86.poi.i.f(SourceFile:233)
	at com.devemux86.poi.PoiLibrary.dialogSearch(SourceFile:116)
	at com.devemux86.cruiser.ck.actionPerformed(SourceFile:241)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028)
	at java.desktop/com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.Exception: No native library is found for os.name=Mac and os.arch=aarch64. path=/org/sqlite/native/Mac/aarch64
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:333)
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:64)
	at org.sqlite.core.NativeDB.load(NativeDB.java:63)
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:235)
	... 55 more
```

**Comment by devemux86** [comment]
@alpha-rudy it seems you using an Apple ARM chip?

Please try Cruiser (Beta):
https://www.dropbox.com/sh/itq3e3d0wr0zp3q/AADZ0BYypUf91GhMVKryZzmba

---

Also do not enable the OpenGL, it currently does not work on Apple ARM chips:
- https://github.com/mapsforge/vtm/issues/1004

**Comment by alpha-rudy** [comment]
> Please try Cruiser (Beta):
> https://www.dropbox.com/sh/itq3e3d0wr0zp3q/AADZ0BYypUf91GhMVKryZzmba

Thanks, @devemux86 , it works!  ^^

> @alpha-rudy it seems you using an Apple ARM chip?

Yes. But is this issue realted to Apple ARM chip (as Java should be platform independed)?  XD

<img width="842" alt="Screenshot 2023-09-05 at 4 00 10 PM" src="https://github.com/mapsforge/mapsforge/assets/12744709/2361131d-ce3c-4a07-83a3-e7e74da531c4">

**Comment by devemux86** [comment]
@alpha-rudy it also depends if the libraries have native files.

The desktop JDBC driver uses native files. They must be built for each CPU architecture.

**Comment by alpha-rudy** [comment]
I see. Thanks, @devemux86.  ^^
