### ISSUE TITLE
Tile cache NPE

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#524]
_From [devemu...@gmail.com](https://code.google.com/u/109528871084914010993/) on September 11, 2014 19:06:00_

Playing with a custom map using the dev branch, after some "WARNING: invalid number of way nodes", a crash happened with the following NPE:

Σεπ 11, 2014 7:59:00 ΜΜ org.mapsforge.map.reader.MapDatabase processWayDataBlock
WARNING: invalid number of way nodes: 0
Exception in thread "LayerManager" java.lang.NullPointerException
    at java.util.LinkedHashMap$Entry.remove(LinkedHashMap.java:332)
    at java.util.LinkedHashMap$Entry.recordAccess(LinkedHashMap.java:356)
    at java.util.LinkedHashMap.get(LinkedHashMap.java:304)
    at org.mapsforge.core.util.WorkingSetCache.setWorkingSet(WorkingSetCache.java:42)
    at org.mapsforge.map.layer.cache.InMemoryTileCache.setWorkingSet(InMemoryTileCache.java:120)
    at org.mapsforge.map.layer.cache.TwoLevelTileCache.setWorkingSet(TwoLevelTileCache.java:93)
    at org.mapsforge.map.layer.TileLayer.draw(TileLayer.java:86)
    at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:91)
    at org.mapsforge.map.util.PausableThread.run(PausableThread.java:140)

Emux

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=524_

**Comment by devemux86** [comment]
Mapsforge has changed a lot since then, can create new issue if still valid.
