### ISSUE TITLE
LabelLayer: AwtCanvas NPE

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#639]
With ```LabelLayer``` is often to have ```AwtCanvas``` calls with it's ```graphics2D``` not set and producing NPE.

**Comment by devemux86** [comment]
Here is the exception:
```java
Exception in thread "pool-4-thread-18" java.lang.NullPointerException
	at org.mapsforge.map.awt.AwtCanvas.setClipDifference(AwtCanvas.java:227)
	at org.mapsforge.map.layer.renderer.CanvasRasterer.fillOutsideAreas(CanvasRasterer.java:107)
	at org.mapsforge.map.layer.renderer.DatabaseRenderer.executeJob(DatabaseRenderer.java:166)
	at org.mapsforge.map.layer.renderer.MapWorkerPool$MapWorker.run(MapWorkerPool.java:116)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by devemux86** [comment]
I pushed a fix to avoid painting map outside background during labels only renderer job.
