### ISSUE TITLE
Accidental NullPointerException

### ISSUE THREAD

**Issue by babobka** [mapsforge/mapsforge#710]
I've got the following exception
```
java.lang.NullPointerException
	at android.graphics.Canvas.drawBitmap(Canvas.java:1269)
	at org.mapsforge.map.android.graphics.AndroidCanvas.drawBitmap(AndroidCanvas.java:59)
	at org.mapsforge.core.mapelements.SymbolContainer.draw(SymbolContainer.java:83)
	at org.mapsforge.map.layer.renderer.CanvasRasterer.drawMapElements(CanvasRasterer.java:77)
	at org.mapsforge.map.layer.renderer.DatabaseRenderer.executeJob(DatabaseRenderer.java:155)
	at org.mapsforge.map.layer.renderer.MapWorkerPool$MapWorker.run(MapWorkerPool.java:119)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:848)
```
It happens (sometimes) if I close my map activity.

**Comment by devemux86** [comment]
Are you following the Mapsforge life cycle as described in wiki [example](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Android-App.md)?

**Comment by babobka** [comment]
No, I was not following. All the code was placed in onCreate(). I will make a fix. Is that ok to add a marker in onCreate()?

**Comment by ludwigb** [comment]
That marker probably caused your NPE, you might have to add an increment
ref count to it.

**Comment by babobka** [comment]
How can I do that?

**Comment by devemux86** [comment]
Check our [Samples](https://github.com/mapsforge/mapsforge/tree/master/Applications/Android/Samples) examples, e.g. ChangingBitmaps.

**Comment by ludwigb** [comment]
I think this is the usual problem with not increasing the ref count on a bit map object.
