### ISSUE TITLE
Multilingual maps: AwtCanvas.drawText zero length string

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#716]
I see the following exception in Java with a custom map, having elements with empty names.
We need to include a check there, but it's strange nobody has complained before.

```java
Exception in thread "pool-4-thread-1" java.lang.IllegalArgumentException: Zero length string passed to TextLayout constructor.
	at java.awt.font.TextLayout.<init>(TextLayout.java:382)
	at org.mapsforge.map.awt.graphics.AwtCanvas.drawText(AwtCanvas.java:143)
	at org.mapsforge.map.awt.graphics.AwtPointTextContainer.draw(AwtPointTextContainer.java:119)
	at org.mapsforge.map.layer.renderer.CanvasRasterer.drawMapElements(CanvasRasterer.java:77)
	at org.mapsforge.map.layer.renderer.DatabaseRenderer.executeJob(DatabaseRenderer.java:155)
	at org.mapsforge.map.layer.renderer.MapWorkerPool$MapWorker.run(MapWorkerPool.java:121)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ludwigb** [comment]
Maybe this is a change that has taken effect with multilingual maps, I
guess before maybe zero length names were not included.
(I have not checked the code but maybe we have a situation where the
default name is "", but other names have values).

**Comment by devemux86** [comment]
Indeed we don't write zero length strings in map file.
But now with multilingual maps (forgot to mention) we may have cases as ```Base\ren\bEnglish``` where the base is empty and finds its way through the rendering mechanism.

**Comment by devemux86** [comment]
Related to multilingual maps #624.

**Comment by devemux86** [comment]
Pushed a fix checking for zero length names prior rendering.
