### ISSUE TITLE
Task Type mapfile-writer doesn't exist.

### ISSUE THREAD

**Issue by coniocharles** [mapsforge/mapsforge#740]
I downloaded the latest version of Osmosis and put it in drive C:
after that i downloaded the mapsforge-map-writer-dev-SNAPSHOT.jar and putted it in
C:\Users\Galvez\AppData\Openstreetmap\Osmosis\Plugins

And after that I used git to run these codes.  
$ /c/Osmosis/bin/osmosis --rb file=/c/Osmosis/bin/philippines-latest.osm.pbf --mapfile-writer file=/tmp/phil.map

after entering that line, i received this error.  
Dec 01, 2015 11:27:40 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Osmosis Version 0.44.1
Dec 01, 2015 11:27:41 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Preparing pipeline.
Dec 01, 2015 11:27:41 AM org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.
org.openstreetmap.osmosis.core.OsmosisRuntimeException: Task type mapfile-writer doesn't exist.
        at org.openstreetmap.osmosis.core.pipeline.common.TaskManagerFactoryRegister.getInstance(TaskManagerFactoryRegister.java:60)
        at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.buildTasks(Pipeline.java:50)
        at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.prepare(Pipeline.java:112)
        at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:86)
        at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:47)

I put the oms.pbf file inside the bin folder.  
What seems to be the problem with what i have done?

**Comment by ludwigb** [comment]
I think this has been discussed on the mailing list a few times, have a look here: 
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!searchin/mapsforge-dev/mapfile-writer$20does$20not$20exist

**Comment by devemux86** [comment]
For questions please use our mailing list:
https://groups.google.com/forum/#!forum/mapsforge-dev

**Comment by coniocharles** [comment]
Problem solved. I put the openstreetmap in to AppData>Roaming Folder then openstreetmap../
thank you.
