### ISSUE TITLE
Marker java.lang.VerifyError

### ISSUE THREAD

**Issue by NamtarR** [mapsforge/mapsforge#752]
Today I tried to update mapsforge libraries in my project from 0.5.2 to 0.6.0. I have a custom class for markers on a map which extends `org.mapsforge.map.layer.overlay.Marker`. Now when I try to run my project on Lollipop+ device it works perfectly, but on pre-Lollipop devices it throws a java.lang.VerifyError exception in constructor.
Here is a log:
```
ru.aspirity.stolbyapp W/dalvikvm: VFY: register1 v4 type 17, wanted 13
ru.aspirity.stolbyapp W/dalvikvm: VFY:  rejecting call to Lorg/mapsforge/map/layer/overlay/Marker;.draw (Lorg/mapsforge/core/model/BoundingBox;BLorg/mapsforge/core/graphics/Canvas;Lorg/mapsforge/core/model/Point;)V
ru.aspirity.stolbyapp W/dalvikvm: VFY:  rejecting opcode 0x6f at 0x0094
ru.aspirity.stolbyapp W/dalvikvm: VFY:  rejected Lru/aspirity/stolby/model/POIMarker;.access$super (Lru/aspirity/stolby/model/POIMarker;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;
ru.aspirity.stolbyapp W/dalvikvm: Verifier rejected class Lru/aspirity/stolby/model/POIMarker;
ru.aspirity.stolbyapp D/AndroidRuntime: Shutting down VM
ru.aspirity.stolbyapp W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4304b160)
ru.aspirity.stolbyapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: ru.aspirity.stolbyapp, PID: 30670
                                                                       java.lang.VerifyError: ru/aspirity/stolby/model/POIMarker
                                                                           at ru.aspirity.stolby.fragments.MapFragment.setupMarkers(MapFragment.java:206)
                                                                           at ru.aspirity.stolby.fragments.MapFragment.onAttach(MapFragment.java:96)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1019)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
                                                                           at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
                                                                           at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
                                                                           at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)
                                                                           at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:547)
                                                                           at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
                                                                           at android.app.Activity.performStart(Activity.java:5241)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2208)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2285)
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:138)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1236)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:149)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5061)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:603)
                                                                           at dalvik.system.NativeStart.main(Native Method)
```
Version 0.5.2 works great but I really wanted to update to 0.6.0 because of new gestures. Thank you in advance.

**Comment by devemux86** [comment]
`java.lang.VerifyError` usually occurs when you have compiled against a different library version than you're using at runtime.

So can you try rebuilding your code against the Mapsforge you want to use?

**Comment by NamtarR** [comment]
It seems I've found a solution - switching to gradle plugin 1.5 from 2.0 alpha solved a problem. Thank you!
