### ISSUE TITLE
NullPointerException in onDestroy

### ISSUE THREAD

**Issue by sytolk** [mapsforge/mapsforge#756]
I have BubbleOverlay extends LocationOverlayMapViewer example and this exception appears after turn screen into Landscape. I have use Proguard too.
```
java.lang.NullPointerException
   at org.mapsforge.map.c.e.n.onDestroy(TileRendererLayer.java:91)
   at org.mapsforge.map.android.view.MapView.c(MapView.java:194)
   at org.mapsforge.map.android.util.MapViewerTemplate.onDestroy(MapViewerTemplate.java:291)
   at org.mapsforge.applications.android.BaseMapActivity.onDestroy(BaseMapActivity.java:174)
   at com.stil.android.BubbleOverlay.onDestroy(BubbleOverlay.java:87)
   at android.app.Activity.performDestroy(Activity.java:5172)
   at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1109)
   at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3261)
   at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3292)
   at android.app.ActivityThread.access$1200(ActivityThread.java:130)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1249)
   at android.os.Handler.dispatchMessage(Handler.java:99)
   at android.os.Looper.loop(Looper.java:137)
   at android.app.ActivityThread.main(ActivityThread.java:4747)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:511)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
   at dalvik.system.NativeStart.main(Native Method)
```
I check if (this.mapDataStore != null) in TileRendererLayer and problem disappears.
```java
@Override
    public void onDestroy() {
        if (this.renderThemeFuture != null) {
            this.renderThemeFuture.decrementRefCount();
        }
        if (this.mapDataStore != null) this.mapDataStore.close();
        super.onDestroy();
    }
```

**Comment by devemux86** [comment]
Can you provide a log without obfuscation?

`TileRendererLayer` should not exist without map data store in the first place.
Though we may overcome the NPE with a check, it's worth seeing why the `mapDataStore` is null there.

Samples does not restart the activities on orientation changes, you do that in your code?

**Comment by devemux86** [comment]
BTW just modified slightly Samples according to your use case and on device orientation changes the activity restarts correctly, the map view and layers are destroyed without NPE.

**Comment by sytolk** [comment]
My bad. Initially I have createTileRendererLayer with mapFile=null next its have filePicker startActivityForResult with Choose/Download map and after Download map file complete onDestroy() with NPE is called.
This check if (mapFile != null) in BaseMapActivity fix this issue.

```
@Override
    protected void createLayers() {
        MapDataStore mapFile = getMapFile();
        if (mapFile != null) {
            TileRendererLayer tileRendererLayer = AndroidUtil.createTileRendererLayer(this.tileCaches.get(0),
                    mapView.getModel().mapViewPosition, mapFile, getRenderTheme(), false, true);
            this.mapView.getLayerManager().getLayers().add(tileRendererLayer);
        }
    }
```

**Comment by devemux86** [comment]
The implementation should not try to create layers with empty / null maps.
If you have changed Samples life cycle you should adapt your code to that.
