### ISSUE TITLE
StrictMode: How to avoid "resource was acquired ... but never released"

### ISSUE THREAD

**Issue by hgoebl** [mapsforge/mapsforge#761]
Maybe I've got too paranoid settings for Android StrictMode. It's not completely deterministic, most likely because the fragment containing the map is in a ViewPager which implements some kind of Fragment-caching. In most cases I can see following stacktrace:

```
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
        java.lang.Throwable: Explicit termination method 'close' not called
at dalvik.system.CloseGuard.open(CloseGuard.java:184)
at java.io.FileInputStream.<init>(FileInputStream.java:78)
at android.app.ContextImpl.openFileInput(ContextImpl.java:980)
at android.content.ContextWrapper.openFileInput(ContextWrapper.java:176)
at org.mapsforge.map.android.graphics.AndroidGraphicFactory.openFileInput(AndroidGraphicFactory.java:276)
at org.mapsforge.map.android.graphics.AndroidSvgBitmapStore.get(AndroidSvgBitmapStore.java:88)
at org.mapsforge.map.android.graphics.AndroidSvgBitmap.getResourceBitmap(AndroidSvgBitmap.java:44)
at org.mapsforge.map.android.graphics.AndroidSvgBitmap.<init>(AndroidSvgBitmap.java:107)
at org.mapsforge.map.android.graphics.AndroidGraphicFactory.renderSvg(AndroidGraphicFactory.java:302)
at org.mapsforge.map.rendertheme.XmlUtils.createBitmap(XmlUtils.java:64)
at org.mapsforge.map.rendertheme.renderinstruction.RenderInstruction.createBitmap(RenderInstruction.java:131)
at org.mapsforge.map.rendertheme.renderinstruction.Symbol.getBitmap(Symbol.java:62)
at org.mapsforge.map.rendertheme.renderinstruction.Caption.<init>(Caption.java:96)
at org.mapsforge.map.rendertheme.rule.RenderThemeHandler.startElement(RenderThemeHandler.java:186)
at org.mapsforge.map.rendertheme.rule.RenderThemeHandler.processRenderTheme(RenderThemeHandler.java:107)
at org.mapsforge.map.rendertheme.rule.RenderThemeHandler.getRenderTheme(RenderThemeHandler.java:67)
at org.mapsforge.map.rendertheme.rule.RenderThemeFuture$RenderThemeCallable.call(RenderThemeFuture.java:60)
at org.mapsforge.map.rendertheme.rule.RenderThemeFuture$RenderThemeCallable.call(RenderThemeFuture.java:43)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.lang.Thread.run(Thread.java:818)
```

Is this caused by wrong usage of mapsforge? Or is it a shortcoming of mapsforge which could be avoided? Should particular StrictMode settings be turned off?

I'm using v0.6.0. Please tell me, if you need further information.

**Comment by devemux86** [comment]
What exactly are your settings?

BTW you can check Mapsforge fragment use in Samples.

**Comment by hgoebl** [comment]
These are my settings:

``` java
StrictMode.ThreadPolicy threadPolicy = new StrictMode.ThreadPolicy.Builder()
        .detectNetwork()
        .detectDiskWrites()
        .detectAll()
      //.permitDiskReads()
        .penaltyLog()
        .penaltyDeathOnNetwork()
        .build();
StrictMode.setThreadPolicy(threadPolicy);

StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
        .detectAll()
        .penaltyLog()
        .build());
```

Thanks for the hint - I'll have another view on the Samples.

**Comment by devemux86** [comment]
Thanks for the settings.

I tested it and indeed the warning appears regardless if we use fragments or not.
It can be easily fixed by closing the aforementioned SVG stream.

We need to perform more tests before pushing something in repository, in case of side effects from that.

**Comment by devemux86** [comment]
Forgot to mention that to test it, use the above settings, open any example in Samples and zoom until the map symbols appear.

**Comment by hgoebl** [comment]
@devemux86 could you send me a patch or tell me where to close the stream? I could test it at the same time while doing a lot of other tests and development.

**Comment by devemux86** [comment]
In `AndroidSvgBitmapStore` we have two streams.

The [output](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map-android/src/main/java/org/mapsforge/map/android/graphics/AndroidSvgBitmapStore.java#L62-L71) could be rewritten:
```java
FileOutputStream outputStream = null;
try {
	outputStream = AndroidGraphicFactory.INSTANCE.openFileOutput(fileName, Context.MODE_PRIVATE);
	if (!this.bitmap.compress(Bitmap.CompressFormat.PNG, 0, outputStream)) {
		LOGGER.warning("SVG Failed to write svg bitmap " + fileName);
	}
} catch (IllegalStateException e) {
	LOGGER.warning("SVG Failed to stream bitmap to file " + fileName);
} catch (FileNotFoundException e) {
	LOGGER.warning("SVG Failed to create file for svg bitmap " + fileName);
} finally {
	IOUtils.closeQuietly(outputStream);
}
```

And [input](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map-android/src/main/java/org/mapsforge/map/android/graphics/AndroidSvgBitmapStore.java#L87-L92) like:
```java
FileInputStream inputStream = null;
try {
	inputStream = AndroidGraphicFactory.INSTANCE.openFileInput(fileName);
	return BitmapFactory.decodeStream(inputStream);
} catch (FileNotFoundException e) {
	// ignore: file is not yet in cache
} finally {
	IOUtils.closeQuietly(inputStream);
}
```

**Comment by hgoebl** [comment]
Thanks @devemux86, I'll try that.
IMO this change should not have any negative impact. A tool like FindBugs would probably warn about this problem by pure static code analysis. I suppose that `bitmap.compress` and `BitmapFactory.decodeStream` are synchronous...

**Comment by devemux86** [comment]
Additional tests didn't show any side effects, so I pushed the closing of the bitmap streams.

**Comment by hgoebl** [comment]
@devemux86 you're welcome. Thanks for this really awesome piece of software :+1:
