### ISSUE TITLE
[POIwriter] java.lang.ClassCastException: org.apache.xerces.jaxp.SAXParserFactoryImpl cannot be cast to javax.xml.parsers.SAXParserFactory

### ISSUE THREAD

**Issue by grinapo** [mapsforge/mapsforge#836]
mapsforge-poi-writer-0.6.1-rc1-jar-with-dependencies.jar (mapwriter plugin works well).

The web says this is a rather common problem in the java world but I (as a non-java guy) don't seem to possess the tools to determine the cause. 

        at javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:126)
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.getXMLReader(AbstractUnmarshallerImpl.java:100)
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:162)
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:171)
        at org.mapsforge.poi.writer.XMLPoiCategoryManager.<init>(XMLPoiCategoryManager.java:60)
        at org.mapsforge.poi.writer.PoiWriter.<init>(PoiWriter.java:116)
        at org.mapsforge.poi.writer.PoiWriter.newInstance(PoiWriter.java:69)
        at org.mapsforge.poi.writer.osmosis.PoiWriterTask.<init>(PoiWriterTask.java:66)
        at org.mapsforge.poi.writer.osmosis.PoiWriterFactory.createTaskManagerImpl(PoiWriterFactory.java:75)
        at org.openstreetmap.osmosis.core.pipeline.common.TaskManagerFactory.createTaskManager(TaskManagerFactory.java:60)
        at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.buildTasks(Pipeline.java:50)
        at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.prepare(Pipeline.java:112)
        at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:86)
        at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:328)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:31)

**Comment by devemux86** [comment]
I cannot confirm the issue, tested both 0.6.1-rc1 map and poi writers with Osmosis 0.44.1 and Java 8.

Can you describe your configuration and where did you put the Mapsforge writer jar (is it alone) ?

**Comment by devemux86** [comment]
Is there still an issue?

**Comment by grinapo** [comment]
Sorry, I am not sure what you wanted to know. The configuration is debian wheezy, stuff is from standard packages, INFO: Osmosis Version 0.43.1, ~/.openstreetmap/osmosis/plugins/ contains only 
mapsforge-map-writer-0.6.1-rc1-jar-with-dependencies.jar and mapsforge-poi-writer-0.6.1-rc1-jar-with-dependencies.jar.

Now I have updated to 0.6.1 release, and got for
`        osmosis --read-pbf  "osm_files/${MAP^}.osm.pbf"  --buffer --sort \
                --tag-transform file="contour/andromaps/tag-transforms.xml" \
                --poi-writer file="${MAP}.poi" preferred-language=hu  2>&1 | tee   $LOG`

`
Jun 15, 2016 4:14:49 PM org.mapsforge.poi.writer.logging.LoggerWrapper log
INFO: POI writer version: mapsforge-poi-writer-0.6.1
Jun 15, 2016 4:14:49 PM org.mapsforge.poi.writer.logging.LoggerWrapper log
INFO: POI format specification version: 1
Jun 15, 2016 4:14:49 PM org.mapsforge.poi.writer.logging.LoggerWrapper log
INFO: Loading categories...
Jun 15, 2016 4:14:49 PM org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.
java.lang.ClassCastException: org.apache.xerces.jaxp.SAXParserFactoryImpl cannot be cast to javax.xml.parsers.SAXParserFactory
        at javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:126)
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.getXMLReader(AbstractUnmarshallerImpl.java:100)
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:162)
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:171)
        at org.mapsforge.poi.writer.XMLPoiCategoryManager.<init>(XMLPoiCategoryManager.java:60)
        at org.mapsforge.poi.writer.PoiWriter.<init>(PoiWriter.java:116)
        at org.mapsforge.poi.writer.PoiWriter.newInstance(PoiWriter.java:69)
        at org.mapsforge.poi.writer.osmosis.PoiWriterTask.<init>(PoiWriterTask.java:66)
        at org.mapsforge.poi.writer.osmosis.PoiWriterFactory.createTaskManagerImpl(PoiWriterFactory.java:75)
        at org.openstreetmap.osmosis.core.pipeline.common.TaskManagerFactory.createTaskManager(TaskManagerFactory.java:60)
        at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.buildTasks(Pipeline.java:50)
        at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.prepare(Pipeline.java:112)
        at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:86)
        at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:328)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:31)
`

**Comment by devemux86** [comment]
Which Java?

Please try with a clean downloaded Osmosis, latest version zip, like `0.44.1`:
http://wiki.openstreetmap.org/wiki/Osmosis#Latest_stable_version

**Comment by grinapo** [comment]
Whatever java is in the wheezy latest packaging. Right now it seems to be
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-2~deb7u1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

osmosis comes from the packaged version, too, which is 0.43.1-2  as of now on the server.

But I have upgraded it for you, now it's
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
and
INFO: Osmosis Version 0.45

...same results.

**Comment by grinapo** [comment]
sorry, a bit different:

  javax.xml.parsers.FactoryConfigurationError: Provider for class javax.xml.parsers.SAXParserFactory cannot be created
        at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:311)
        at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:267)
        at javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:127)
        at com.sun.xml.internal.bind.v2.util.XmlFactory.createParserFactory(XmlFactory.java:116)
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.getXMLReader(UnmarshallerImpl.java:139)
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:162)
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:171)
        at org.mapsforge.poi.writer.XMLPoiCategoryManager.<init>(XMLPoiCategoryManager.java:60)
        at org.mapsforge.poi.writer.PoiWriter.<init>(PoiWriter.java:116)
        at org.mapsforge.poi.writer.PoiWriter.newInstance(PoiWriter.java:69)
        at org.mapsforge.poi.writer.osmosis.PoiWriterTask.<init>(PoiWriterTask.java:66)
        at org.mapsforge.poi.writer.osmosis.PoiWriterFactory.createTaskManagerImpl(PoiWriterFactory.java:75)
        at org.openstreetmap.osmosis.core.pipeline.common.TaskManagerFactory.createTaskManager(TaskManagerFactory.java:60)
        at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.buildTasks(Pipeline.java:51)
        at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.prepare(Pipeline.java:112)
        at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:86)
        at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:328)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:31)
Caused by: java.lang.RuntimeException: Provider for class javax.xml.parsers.SAXParserFactory cannot be created
        at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:308)
        ... 26 more
Caused by: java.util.ServiceConfigurationError: javax.xml.parsers.SAXParserFactory: Provider org.apache.xerces.jaxp.SAXParserFactoryImpl not a subtype
        at java.util.ServiceLoader.fail(ServiceLoader.java:239)
        at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at javax.xml.parsers.FactoryFinder$1.run(FactoryFinder.java:294)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:289)
        ... 26 more

**Comment by grinapo** [comment]
It is true, however, that plexus.conf contains that:
# https://code.google.com/p/mapsforge/issues/detail?id=303#c4
load /usr/share/java/xalan2.jar

without it osmosis won't work.

**Comment by devemux86** [comment]
You're using the linux distribution's Osmosis?
Have you tried with a downloaded Osmosis zip from its site (as recommended above)?
In it, there is not such entry in `plexus.conf` with absolute path system dependencies.

**Comment by grinapo** [comment]
*sigh* yes, in the past, and it resulted random crashes, incompatibilities between various libs and system components and random errors between minor versions after upgrades. It was a Maintainability Hell™ - usually related to mapfile-writer. I'll try to check poiwriter with a custom osmosis.

**Comment by devemux86** [comment]
Closing here, if there are additional issues, let's continue the discussion in the forum.
