### ISSUE TITLE
mapsforge NullPointer exception while cleaning map

### ISSUE THREAD

**Issue by mendinskis** [mapsforge/mapsforge#846]
I'm using mapsforge 0.6.0 version. I have a fragment where I put my map. I also add pointers into the map. When I open new fragment most of the time app crash and gives me
```
 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                                                                    at org.mapsforge.map.android.graphics.AndroidBitmap.getWidth(AndroidBitmap.java:114)
                                                                                                    at org.mapsforge.map.layer.overlay.Marker.draw(Marker.java:72)
                                                                                                    at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:90)
                                                                                                    at org.mapsforge.map.util.PausableThread.run(PausableThread.java:140)
```

I noticed that in version 0.6.1 this is fixed however I need to use 0.6.0. Is it possible to be fixed? Thank you

here's my onDestroy method
```

@Override
    protected void onDestroy() {
        mapView.destroyAll();
        AndroidGraphicFactory.clearResourceMemoryCache();
        super.onDestroy();
    }
```

I also noticed that if I clear layers manually app gives this exception more rarely (but still the problem exists)

```
@Override
    protected void onDestroy() {
        mapView.getLayerManager().getLayers().clear();
        mapView.destroyAll();
        AndroidGraphicFactory.clearResourceMemoryCache();
        super.onDestroy();
    }
```

**Comment by devemux86** [comment]
I don't know your implementation or what's called when the exception happens.
Following [Getting-Started-Android-App](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Android-App.md) guide for Mapsforge life cycle is usually the safest way.

Also it's always recommend to advance to newest release for having the latest fixes.

_We don't have the resources to support but the latest release._
