### ISSUE TITLE
If map fail size is differend throws an unhandled exception

### ISSUE THREAD

**Issue by sytolk** [mapsforge/mapsforge#855]
Lets developer to handle MapFileException exception. If download of map fail interrupt map size will be different and developer wants to handle exception and start download/resume again.

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=Intent { (has extras) }} to activity {com.opentaxi.android/com.opentaxi.android.LongPressMapAction_}: org.mapsforge.map.e.a.a: invalid file size: 35786361
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3587)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3630)
	at android.app.ActivityThread.access$1300(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5283)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
Caused by: org.mapsforge.map.e.a.a: invalid file size: 35786361
	at org.mapsforge.map.e.d.<init>(MapFile.java:244)
	at org.mapsforge.map.e.d.<init>(MapFile.java:205)
	at org.mapsforge.applications.android.BaseMapActivity.getMapFile(BaseMapActivity.java:405)
	at org.mapsforge.applications.android.LocationOverlayMapViewer.onActivityResult(LocationOverlayMapViewer.java:94)
	at android.app.Activity.dispatchActivityResult(Activity.java:6178)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3583)
	... 10 more
org.mapsforge.map.e.a.a: invalid file size: 35786361
	at org.mapsforge.map.e.d.<init>(MapFile.java:244)
	at org.mapsforge.map.e.d.<init>(MapFile.java:205)
	at org.mapsforge.applications.android.BaseMapActivity.getMapFile(BaseMapActivity.java:405)
	at org.mapsforge.applications.android.LocationOverlayMapViewer.onActivityResult(LocationOverlayMapViewer.java:94)
	at android.app.Activity.dispatchActivityResult(Activity.java:6178)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3583)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3630)
	at android.app.ActivityThread.access$1300(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5283)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
```

**Comment by devemux86** [comment]
Can you provide a log without obfuscation for us to understand what to read?

**Comment by sytolk** [comment]
It`s easy for me to provide PR

**Comment by devemux86** [comment]
In any case `MapFile` constructor throws a `MapFileException` if map file is invalid.
And there are many more reasons than just a corrupted download, for that to happen.
So what's exactly the need here?

**Comment by devemux86** [comment]
>It`s easy for me to provide PR

First we need to understand the problem.

**Comment by sytolk** [comment]
Ok let me check this fix

**Comment by sytolk** [comment]
The problem is that I have not catch MapFileException :) MapFile trows exception thanks

**Comment by applantation** [comment]
Probably best to check file size from header against actual size after
download, not difficult.

On Jul 14, 2016 20:51, "Stanimir" <notifications@github.com> wrote:

Lets developer to handle MapFileException exception. If download of map
fail interrupt map size will be different and developer want to handle
exception and start download/resume again.

java.lang.RuntimeException: Failure delivering result
ResultInfo{who=null, request=0, result=-1, data=Intent { (has extras)
}} to activity {com.opentaxi.android/com.opentaxi.android.LongPressMapAction_}:
org.mapsforge.map.e.a.a: invalid file size: 35786361
    at android.app.ActivityThread.deliverResults(ActivityThread.java:3587)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3630)
    at android.app.ActivityThread.access$1300(ActivityThread.java:151)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5283)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
Caused by: org.mapsforge.map.e.a.a: invalid file size: 35786361
    at org.mapsforge.map.e.d.<init>(MapFile.java:244)
    at org.mapsforge.map.e.d.<init>(MapFile.java:205)
    at org.mapsforge.applications.android.BaseMapActivity.getMapFile(BaseMapActivity.java:405)
    at org.mapsforge.applications.android.LocationOverlayMapViewer.onActivityResult(LocationOverlayMapViewer.java:94)
    at android.app.Activity.dispatchActivityResult(Activity.java:6178)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:3583)
    ... 10 more
org.mapsforge.map.e.a.a: invalid file size: 35786361
    at org.mapsforge.map.e.d.<init>(MapFile.java:244)
    at org.mapsforge.map.e.d.<init>(MapFile.java:205)
    at org.mapsforge.applications.android.BaseMapActivity.getMapFile(BaseMapActivity.java:405)
    at org.mapsforge.applications.android.LocationOverlayMapViewer.onActivityResult(LocationOverlayMapViewer.java:94)
    at android.app.Activity.dispatchActivityResult(Activity.java:6178)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:3583)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3630)
    at android.app.ActivityThread.access$1300(ActivityThread.java:151)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5283)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mapsforge/mapsforge/issues/855>, or mute the thread
<https://github.com/notifications/unsubscribe/ACKd_2kylf0UbEkyMV5fJTmOlPMP5E3Tks5qVjDGgaJpZM4JMZq->
.
