### ISSUE TITLE
MapFileException: cannot read file:

### ISSUE THREAD

**Issue by Caspain** [mapsforge/mapsforge#906]
Cannot read file. at org.mapsforge.map.reader.MapFile.<init>(MapFile.java:227)
                                                                      at org.mapsforge.map.reader.MapFile.<init>(MapFile.java:205)
                                                                      at android.code.caspain.appo.MainActivity.onCreate(MainActivity.java:59)
                                                                      at android.app.Activity.performCreate(Activity.java:6445)
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
                                                                      at android.app.ActivityThread.access$900(ActivityThread.java:157)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5477)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by devemux86** [comment]
At that point there is a regular `File.canRead()` check which fails in your case.
So see where you have your map file, if you have proper access to that area, like read permission, etc.

For questions please use our forum:
https://groups.google.com/group/mapsforge-dev

**Comment by jahongir9779** [comment]
hello i'm receiving File.canRead false, and ideas?

**Comment by devemux86** [comment]
See above [comment](https://github.com/mapsforge/mapsforge/issues/906#issuecomment-263801795) for what to check.

**Comment by jahongir9779** [comment]
i checked, but couldn't find related issue

**Comment by devemux86** [comment]
Where do you have the map file?
What Android version and is there the relevant permission in manifest?

**Comment by jahongir9779** [comment]
map file is in the root folder of sdcard, it can reach the file but cannot read, b coz i checked with wrong file name and it said file does not exist, but with right name and direction it says cannot read file...
may permissions are 
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>

**Comment by jahongir9779** [comment]
OMG, thanx, i've found the answer, i was developing on android 6, so i had to manually grant permission in my app thanx a lot for your time
