### ISSUE TITLE
NullPointerException from automatic report

### ISSUE THREAD

**Issue by wojtek-abakus** [mapsforge/mapsforge#951]
Hello.

When I was looking through automatic Google reports I've noticed a bug in MapsForge.

This is all i have:
Android 5.1, Galaxy Xcover3 (xcover3lte), version 0.8.0 with hardware acceleration enabled

java.lang.NullPointerException: Attempt to invoke virtual method 'org.mapsforge.map.layer.Layers org.mapsforge.map.layer.LayerManager.getLayers()' on a null object reference
	at org.mapsforge.map.android.input.TouchGestureHandler.onSingleTapConfirmed(TouchGestureHandler.java:232)
	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:273)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5912)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

**Comment by ludwigb** [comment]
Just to understand the background: your app generally runs fine on most
Android devices, you just see this error in a large install base?

It looks like one object (the LayerManager) was not initialized. Do you
have any hunch what is happening? How are your users interacting with your
app?

**Comment by wojtek-abakus** [comment]
The app generally runs fine, only one error like this with 10 000 users.
Map is shown from a WMS service, only adding some markers.

**Comment by devemux86** [comment]
`LaunchManager` is initialized in `MapView` creation and set to null in `MapView.destroy`.
So would need to check the use of Mapsforge in app life cycle.

**Comment by wojtek-abakus** [comment]
I'm aware that probably the user closed the map fragment, but how did the tap event got delivered to that destroyed MapView is the tricky part.
