### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for void jsqlite.Database.internal_init()

### ISSUE THREAD

**Issue by anelfdz** [mapsforge/mapsforge#960]
I'm traying to reproduce the POI search example and I getting this error:
```
java.lang.UnsatisfiedLinkError: No implementation found for void jsqlite.Database.internal_init() (tried Java_jsqlite_Database_internal_1init and Java_jsqlite_Database_internal_1init__)
                                                        at jsqlite.Database.internal_init(Native Method)
                                                        at jsqlite.Database.<clinit>(Database.java:964)
                                                        at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManager.createOrOpenDBFile(AndroidPoiPersistenceManager.java:169)
                                                        at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManager.<init>(AndroidPoiPersistenceManager.java:63)
                                                        at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManagerFactory.getPoiPersistenceManager(AndroidPoiPersistenceManagerFactory.java:42)
                                                        at org.mapsforge.poi.android.storage.AndroidPoiPersistenceManagerFactory.getPoiPersistenceManager(AndroidPoiPersistenceManagerFactory.java:32)
```

**Comment by devemux86** [comment]
Have you included all necessary dependencies in your project (like the native libs)?

You can check the [integration guide](https://github.com/mapsforge/mapsforge/blob/master/docs/Integration.md#poi) for more details.

**Comment by devemux86** [comment]
For further questions regarding Mapsforge usage, please use our [forum](https://groups.google.com/group/mapsforge-dev).

**Comment by typebrook** [comment]
Thanks! It works for me.
