### ISSUE TITLE
map-writer: more than 15 tag aren't supported

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge#971]
Trying this sample map [dienten_V4.zip](https://github.com/mapsforge/mapsforge/files/1116258/dienten_V4.zip) we have empty tiles with exceptions:

```java
org.mapsforge.map.reader.MapFile processBlocks
SEVERE: 25543
java.lang.ArrayIndexOutOfBoundsException: 25543
	at org.mapsforge.map.reader.ReadBuffer.readSignedInt(ReadBuffer.java:176)
	at org.mapsforge.map.reader.MapFile.decodeWayNodesSingleDelta(MapFile.java:358)
	at org.mapsforge.map.reader.MapFile.processWayDataBlock(MapFile.java:685)
	at org.mapsforge.map.reader.MapFile.processWays(MapFile.java:787)
	at org.mapsforge.map.reader.MapFile.processBlock(MapFile.java:455)
	at org.mapsforge.map.reader.MapFile.processBlocks(MapFile.java:562)
	at org.mapsforge.map.reader.MapFile.readMapData(MapFile.java:859)
	at org.mapsforge.map.reader.MapFile.readMapData(MapFile.java:834)
	at org.mapsforge.map.datastore.MultiMapDataStore.readMapData(MultiMapDataStore.java:148)
	at org.mapsforge.map.datastore.MultiMapDataStore.readMapData(MultiMapDataStore.java:137)
	at org.mapsforge.map.layer.renderer.DatabaseRenderer.executeJob(DatabaseRenderer.java:94)
	at org.mapsforge.map.layer.renderer.MapWorkerPool$MapWorker.run(MapWorkerPool.java:155)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by devemux86** [comment]
Discussion in [forum](https://groups.google.com/forum/#!topic/mapsforge-dev/kQKfCMGk2Ec).

**Comment by devemux86** [comment]
Like @ludwigb mentions in forum, issue appears being in map-writer.

I attach for debug (by Christian / OpenAndroMaps):
- [dienten_merged_Error.osm](https://github.com/mapsforge/mapsforge/files/1133030/dienten_merged_Error.zip) with all tags, creating a map with some empty tiles
- [dienten_merged_OK.osm](https://github.com/mapsforge/mapsforge/files/1133032/dienten_merged_OK.zip) with lesser tags, creating a correct map
- [tag-mapping.xml](https://github.com/mapsforge/mapsforge/files/1133033/tag-mapping.zip) needed by above osm files

**Comment by devemux86** [comment]
@Gustl22 has put the necessary map-writer checks via merged PR #1006, so we can close here.

**Comment by ravivarmahattaraki** [comment]
HI I am getting below exception
**java.lang.RuntimeException: more than 15 tags aren't supported**
How i can resolve it?

java.lang.RuntimeException: more than 15 tags aren't supported
        at org.mapsforge.map.writer.MapFileWriter.infoBytePoiLayerAndTagAmount(MapFileWriter.java:455)
        at org.mapsforge.map.writer.MapFileWriter.processPOI(MapFileWriter.java:517)
        at org.mapsforge.map.writer.MapFileWriter.processTile(MapFileWriter.java:861)
        at org.mapsforge.map.writer.MapFileWriter.writeSubfile(MapFileWriter.java:977)
        at org.mapsforge.map.writer.MapFileWriter.writeFile(MapFileWriter.java:375)
        at org.mapsforge.map.writer.osmosis.MapFileWriterTask.complete(MapFileWriterTask.java:113)
        at org.openstreetmap.osmosis.tagtransform.impl.TransformHelper.complete(TransformHelper.java:95)
        at crosby.binary.osmosis.OsmosisBinaryParser.complete(OsmosisBinaryParser.java:35)
        at org.openstreetmap.osmosis.osmbinary.file.BlockInputStream.process(BlockInputStream.java:37)
        at crosby.binary.osmosis.OsmosisReader.run(OsmosisReader.java:45)
        at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by devemux86** [comment]
_For questions please use the Discussions._

> How i can resolve it?

Review your map creation process (e.g. tag-mapping) and do not use more than 15 tags per element.
